url: "https://abbynicoleyee.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
disqus_shortname: 'abbynicoleyee-github-io-website'
disqus:
  shortname: abbynicoleyee-github-io-website
comments: true
jekyll-disqus:
  shortname:'abbynicoleyee-github-io-website' 
  post_selector: 'include.post'
  ui:
    layouts:
    - 'post'
plugins:
  - jekyll-sitemap
  - jekyll-disqus-plugin
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename/
 
include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md
