#-------------------------------
# General Site Settings

title: Abby Nicole Yee
description: Personal website of writer, composer, and artist Abby Nicole Yee
copyright: Website by [Hal Y. Zhang](https://abbynicoleyee.github.io/website/design) 2024.

menu:
- {name: About/Contact, link: 'https://abbynicoleyee.github.io/website/about'}
- {name: Highlights, link: 'https://abbynicoleyee.github.io/website/highlights'}
- {name: Writing, link: 'https://abbynicoleyee.github.io/website/writing'}
- {name: Blog, link: 'https://abbynicoleyee.github.io/website/blog'}


#-------------------------------
# Google Analytics Section

# google-analytics: UA-101186181-1

#-------------------------------
# Hero Section
# hero:
  # hero-title: Hey there! 🌐

#-------------------------------
# Highlights (Section and Page)

# Highlights Home Section
works-home-items:
  - image : "assets/images/clarkesworld.JPG"
    url: "highlights#clarkesworld"

  - image : "assets/images/panicattack.PNG"
    url: "highlights#panicattack"

  - image : "assets/images/hawflakes.JPG"
    url: "highlights#hawflakes"

#-------------------------------
# Writing Page

writing-label:
- {
    title : "Short Story",
    type : "Short Story"
  }
- {
    title : "Novella",
    type : "Novella"
  }
- {
    title : "Poetry",
    type : "Poetry"
  }
- {
    title : "Creative Nonfiction",
    type : "Creative Nonfiction"
  }
- {
    title : "Music",
    type : "Music"
  }
  
writing-items:
- quote: "Clara knew where this was going. She always had the same answer, but it was always off-the-record, and Manuel could twist whatever she says. The Russian Sputnik II spacecraft wasn’t designed to be recovered, and Laika died of overheating hours after launch. They could all agree the ethics during the Cold War’s Space Race weren’t the best."
  date: '2024-10-01'
  item-types:
  - type: Short Story
  - type: selected
  link: https://clarkesworldmagazine.com/yee_10_24/
  name: A Space O/pera
  publisher: Clarkesworld
  words: 4080
  notes:
      - Read by [Kate Baker](https://clarkesworldmagazine.com/audio_10_24/) for the Clarkesworld Podcast, 2024.
- quote: Instrumental lo-fi song with a raw irregular rhythm and gritty MIDI samples from Ableton.
  date: '2024-11-30'
  item-types:
  - type: Music
  - type: selected
  link: https://open.spotify.com/album/5gClrNi6H9iDnhlfXWJ4ml
  name: Out of Step
  publisher: TuneCore
  words: 0
  notes:
      - Available on [Spotify](https://open.spotify.com/album/5gClrNi6H9iDnhlfXWJ4ml), [Apple Music](http://itunes.apple.com/album/id/1782729896), [YouTube](https://youtu.be/7lJubstL3fI?si=TyZdfl4RRjSub4Sz), and more.
- quote: Instrumental song with heavy strings and beats composed in MuseScore.
  date: '2024-06-10'
  item-types:
  - type: Music
  - type: selected
  link: https://open.spotify.com/album/2nBqg1WWu6OYWLAAZTEYJO
  name: Panic Attack
  publisher: TuneCore
  words: 0
  notes:
      - Available on [Spotify](https://open.spotify.com/album/2nBqg1WWu6OYWLAAZTEYJO), [Apple Music](http://itunes.apple.com/album/id/1759897239), [YouTube](https://youtu.be/z4HLY-1Gk5U?si=PZELp-nKBLqFVpty), and more. 
- quote: "It—flat and dimensionless and not made of paper anymore but not flesh either but not nothing and then the lights went off before you could see it unravel into—"
  date: '2018-12-09'
  item-types:
  - type: Short Story
  - type: selected
  link: https://philippinesgraphic.com.ph/2018/12/09/blank/
  name: Blank
  publisher: The Philippines Graphic
  words: 2100
- quote: “You know, Abby, you have really big legs,” she said. “You should call them logs.”
  date: '2017-03-28'
  item-types:
  - type: Creative Nonfiction
  - type: selected
  link: https://opinion.inquirer.net/102787/elephant-not-exist
  name: The elephant does not exist
  publisher: Inquirer Young Blood
  words: 1106

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-form-url: f/mkgndaab
#-------------------------------
# Blog Section

posts: 
- image : "assets/images/hawflakes.JPG"
  url: "https://abbynicoleyee.github.io/website/post1"
  title: Test blog
  date: '2017-03-28'
  content: Hello
  excerpt: Hello

#-------------------------------
# Colophon

colophon:
  - This site is forked and modified from author Hal Y. Zhang's [website](https://halyzhang.com/) and uses [Jekyll](https://jekyllrb.com/). It is based on the [Kross](https://github.com/themefisher/kross-jekyll) theme from Themefisher under the MIT license.
    It is hosted by [GitHub Pages](https://pages.github.com/). [PT Serif](https://fonts.google.com/specimen/PT+Serif) is the body font. Hypercubes illustrated by Abby.
